fix code quality issues
bkeepers/dotenv pull request #425
Opened 2021-02-12 10:06 UTC by withshubh

#### Description
This PR fixes a few issues that were affecting the code quality.

#### Summary of changes
- Error classes should inherit from `RuntimeError` instead of `Exception`
- Fix parameters being passed to `expand_path`
- Update config files with latest cops/parameters

2021-02-24 11:33 UTC, withshubh commented
@dsander :wave: Please review this PR! :sparkles:

2021-04-02 17:27 UTC, withshubh commented
Hi @bkeepers Please review this PR :sparkles:

2021-04-09 23:46 UTC, bkeepers requested changes
Hi @withshubh, thanks for the pull request! Can you explain why these are considered code quality issues?

2021-04-09 23:46 UTC, bkeepers commented on lib/dotenv/parser.rb
> +  class FormatError < RuntimeError; end
Is this causing issues, or what is the motivation to switch from SyntaxError to RuntimeError?

2021-06-01 12:44 UTC, bkeepers commented
@withshubh I’m going to close this since I didn’t get a reply, but let me know if you want to discuss and have it reopened.

2021-06-01 12:44 UTC, closed without merging